version: "3"

services:
  nginx:
    image: "nginx:latest"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      # default.conf
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      # docRoot
      - "./nginx.docRoot:/var/www/public"
      # app mounted on "/ledger/"
      - "../Frontend/dist:/var/www/ledger/dist"
  tomcat:
    image: "tomcat:9.0.45-jdk8-adoptopenjdk-hotspot"
    restart: "always"
    ports:
      - "8080:8080"
    volumes:
      # webapps
      - "./tomcat.webapps:/usr/local/tomcat/webapps"
